#!/usr/bin/env python2

import os
import sys
import json
import subprocess
import argparse
import ConfigParser

def upc(args, config):
    drush = config.get("common", "DrushCommand")
    with open(os.devnull) as DEVNULL:
        try:
            cmd = "git status"
            subprocess.check_call(cmd.split(" "), stderr=DEVNULL)
        except subprocess.CalledProcessError:
            print "Your site doesn't seem to manage with git"
            sys.exit(1)
        
        cmd = drush + " ups --format=json --security-only"
        update_status = subprocess.check_output(cmd, shell=True, stderr=DEVNULL)
        # workaround for "docker-compose run -T" inconsistently outputs stdout / stderr?
        # see also: https://github.com/docker/compose/issues/3267
        start = update_status.index("{")
        json_status = json.loads(update_status[update_status.index("{"):])
        modules = json_status.keys()
        modules.remove("drupal")
        
        for module in modules:
            name = json_status[module]["name"]
            if args.module != 'all' and args.module != name:
                continue

            path = json_status[module]["path"]
            matched_update = False
            if args.version == False:
                matched_update = json_status[module]["security updates"][0]
            else:
                for update in json_status[module]["security updates"]:
                    if args.version == update["version"]:
                        print update["version"]
                        matched_update = update

            if matched_update == False:
                print "%s %s cann't found in releases, please check project page in drupal.org" % (name, args.version)
                sys.exit(1)

            version = matched_update["version"]
            release_link = matched_update["release_link"]
        
            cmd = drush + " upc -y %(name)s %(version)s" % locals()
            subprocess.call(cmd, shell=True, stderr=DEVNULL)
        
            cmd = "git add -A %(path)s" % locals()
            subprocess.call(cmd, shell=True, stdout=DEVNULL, stderr=DEVNULL)
        
            cmd = 'git commit -m "%(name)s: update to %(version)s for security\n\n%(release_link)s"' % locals()
            subprocess.call(cmd, shell=True, stdout=DEVNULL, stderr=DEVNULL)

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()
parser_upc = subparsers.add_parser('upc', help='Execute drush pm-updatecode and update your git repositoy.')
parser_upc.set_defaults(func=upc)
parser_upc.add_argument('--module', action='store', default='all',
    help='module name to update. If omitted, all modules expect core will be updated.')
parser_upc.add_argument('--version', action='store', default=False,
    help='version of the module to update. If omitted, the latest version will be used.')


args = parser.parse_args() 

config = ConfigParser.ConfigParser()
config.read([os.path.join(os.path.dirname(os.path.realpath(__file__)), 'drush-scm.ini'), os.path.expanduser('~/.drush-scm/drush-scm.ini')])

args.func(args, config)
